apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ankka-controlplane-db-restored
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ankka-backups
        serverName: SET
  postgresql:
    parameters:
      archive_timeout: "60s"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ankka-controlplane-db-restored-base
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: SET
