/**
 * The client's schemas against what the platform's own codecs write. The fixtures are generated by
 * `ControlPlaneFixturesSuite` in controlplane-api; a change on the Scala side that this side does not
 * follow fails here, naming the type.
 */
import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { schemasByType } from "../src/client/schemas.ts";

const dir = fileURLToPath(new URL("../fixtures/control-plane/", import.meta.url));

/** Forwarded as the text a person gave, never decoded: the control plane is what validates them. */
const opaque = new Set(["ServiceDescriptor", "ServiceSpec"]);

/** The value with `undefined` fields and empty defaults gone, as a JSON writer that omits them would leave it. */
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .filter(([, v]) => v !== undefined && v !== null)
        .map(([k, v]) => [k, canonical(v)])
        .sort(([a], [b]) => (a as string).localeCompare(b as string)),
    );
  }
  return value;
}

const files = readdirSync(dir).filter((f) => f.endsWith(".json"));

describe("the client's schemas decode what the platform writes", () => {
  test("there are fixtures to check", () => {
    assert.ok(files.length >= 40, `only ${files.length} fixture files`);
  });

  for (const file of files) {
    const { type, json } = JSON.parse(readFileSync(dir + file, "utf8")) as { type: string; json: unknown };
    if (opaque.has(type)) continue;
    const minimal = file.endsWith(".minimal.json");
    test(`${file}`, () => {
      const schema = schemasByType[type];
      assert.ok(schema, `no schema for the wire type ${type}`);
      const values = Array.isArray(json) ? json : [json];
      for (const value of values) {
        const decoded = schema.parse(value);
        if (!minimal) {
          // Everything the platform wrote survives decoding: a field the schema does not know would
          // be dropped here, and the comparison names it.
          assert.deepEqual(canonical(pick(decoded, value)), canonical(value));
        }
      }
    });
  }

  test("every schema the client decodes with has a fixture", () => {
    const covered = new Set(files.map((f) => JSON.parse(readFileSync(dir + f, "utf8")).type as string));
    // Types that appear only nested in another type's fixture, or that the console writes rather than reads.
    const nested = new Set(["OrganizationMembership", "Usage", "RegistrySummary", "HistoryActor", "MemberSummary", "InvitationSummary", "Owner", "ErrorBody"]);
    const missing = Object.keys(schemasByType).filter((t) => !covered.has(t) && !nested.has(t));
    assert.deepEqual(missing, []);
  });
});

/** The decoded value restricted to the keys the wire value has, so defaults the schema fills in are not counted as differences. */
function pick(decoded: unknown, wire: unknown): unknown {
  if (Array.isArray(decoded) && Array.isArray(wire)) return decoded.map((d, i) => pick(d, wire[i]));
  if (decoded && typeof decoded === "object" && wire && typeof wire === "object" && !Array.isArray(wire)) {
    const w = wire as Record<string, unknown>;
    const d = decoded as Record<string, unknown>;
    return Object.fromEntries(Object.keys(w).map((k) => [k, pick(d[k], w[k])]));
  }
  return decoded;
}
