/**
 * Every acceptance scenario the browser suite must exercise, by the id the specification gives it.
 * A Playwright test covers a scenario by starting its title with the id: `test("US1-3 sign-out …")`.
 * The suite's own scenarios test fails when an id here has no test (SC-011).
 */
export const scenarios: Record<string, string> = {
  "US1-1": "a deep link sends a stranger to sign in and back to the deep link",
  "US1-2": "no token in any cookie, storage or response body; the cookie is HttpOnly, same-site, small",
  "US1-3": "sign-out ends the console's session and the identity provider's",
  "US1-4": "an ended session sends the person to sign in and back",
  "US1-5": "a callback with a state the console did not issue is refused",
  "US1-6": "a return-to naming another site lands on the front page",
  "US1-7": "a session works on every instance and survives an instance restarting",
  "US1-8": "an unreachable identity provider is explained, and the session is kept",
  "US2-1": "a member sees their organizations with their role, and nothing else",
  "US2-2": "a platform administrator sees every organization",
  "US2-3": "creating an organization lands on it, read by id",
  "US2-4": "an owner renames an organization; a member is not offered it",
  "US2-5": "an empty organization is deleted; a non-empty one is refused with the reason",
  "US2-6": "a deleted id cannot be reused, and the page says so",
  "US2-7": "projects are created, renamed and deleted; one with services cannot be deleted",
  "US2-8": "where only administrators create organizations, the refusal names the sign-up address",
  "US3-1": "a project lists its services with state, instances, image, generation and hostname",
  "US3-2": "a service shows every status field and its attributed history",
  "US3-3": "a descriptor is applied, and a refused one shows every problem",
  "US3-4": "pause, resume, restart, expose and unexpose take effect and show the control plane's state",
  "US3-4a": "a service page and a listing follow the control plane's changes live",
  "US3-5": "an exposed service's hostname is a link",
  "US3-6": "logs with the CLI's choices, followed live",
  "TOPO-1": "a member reads a deployed service's topology, merged across its instances, followed live",
  "TOPO-2": "an instance that did not answer leaves the topology partial and is named",
  "US3-7": "a deleted service is gone, and applying the name again continues its generation",
  "US3-8": "a suspended service reads Suspended and its operations are refused, not hidden",
  "US4-1": "an owner sees members and pending invitations",
  "US4-2": "an invitation is claimed when the invited person signs in",
  "US4-3": "roles change and members are removed; the last owner cannot be",
  "US4-4": "a member sees the list and no controls; a machine is shown as one",
  "US4-5": "a deploy token's secret is shown once, and not after a reload",
  "US4-6": "a revoked token is refused",
  "US4-7": "an administrator disables and enables an organization",
  "US4-8": "an administrator sets and clears a quota",
  "US7-1": "every page is rendered before any script runs",
  "US7-2": "navigation with scripts does not reload the document",
  "US7-3": "every operation works with scripts disabled",
  "US7-4": "a second submission while the first is in flight performs nothing",
};
