nakka.http {
  interface = "0.0.0.0"
  interface = ${?NAKKA_HTTP_INTERFACE}

  port = 9000
  port = ${?NAKKA_HTTP_PORT}

  # How long to wait for a request body to arrive in full.
  body-timeout = 10s
}
